"""alterando o lazy do model Campi

Revision ID: 1887ec25c09f
Revises: e96fbd4b28c7
Create Date: 2025-10-02 11:56:57.262400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1887ec25c09f'
down_revision: Union[str, Sequence[str], None] = 'e96fbd4b28c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'campi', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campi', type_='unique')
    # ### end Alembic commands ###
