"""implementando instancia unica na coluna name de cursos

Revision ID: 1f6eb35f3969
Revises: a7b7587bc585
Create Date: 2025-10-01 20:25:45.028050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6eb35f3969'
down_revision: Union[str, Sequence[str], None] = 'a7b7587bc585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('area_ocde', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'cursos', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cursos', type_='unique')
    op.drop_column('cursos', 'area_ocde')
    # ### end Alembic commands ###
