"""att db

Revision ID: 31230604560e
Revises: 9c31d9e3ba5c
Create Date: 2025-09-24 21:41:15.984992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31230604560e'
down_revision: Union[str, Sequence[str], None] = '9c31d9e3ba5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.create_unique_constraint(None, 'municipios', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'municipios', type_='unique')
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    # ### end Alembic commands ###
