"""alterando a coluna name de cursos

Revision ID: 6d92ae044816
Revises: 158cc2ad80de
Create Date: 2025-10-03 15:33:21.589871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d92ae044816'
down_revision: Union[str, Sequence[str], None] = '158cc2ad80de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cursos_name_key'), 'cursos', type_='unique')
    op.create_unique_constraint(None, 'cursos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cursos', type_='unique')
    op.create_unique_constraint(op.f('cursos_name_key'), 'cursos', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
