"""creating tables > estados, cidades and add in db

Revision ID: 9c31d9e3ba5c
Revises: f8b2d5740555
Create Date: 2025-09-23 20:03:42.377986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c31d9e3ba5c'
down_revision: Union[str, Sequence[str], None] = 'f8b2d5740555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cidade_state', 'municipios', ['name', 'state_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cidade_state', 'municipios', type_='unique')
    # ### end Alembic commands ###
