"""retirando a coluna 'quantity_campus' do modelo ies 

Revision ID: 9f5603a1178d
Revises: d7701456e846
Create Date: 2025-10-02 14:04:46.317464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5603a1178d'
down_revision: Union[str, Sequence[str], None] = 'd7701456e846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instituicoes', 'quantity_campus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instituicoes', sa.Column('quantity_campus', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
