"""adicionando coluna 'is_admin' na tabela usuarios 

Revision ID: a63c82e23105
Revises: ae7e96f46fee
Create Date: 2025-10-10 10:05:08.173806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63c82e23105'
down_revision: Union[str, Sequence[str], None] = 'ae7e96f46fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_curso_cidade', 'cursos_localização', ['course_id', 'city_id'])
    op.add_column('usuarios', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_admin')
    op.drop_constraint('uix_curso_cidade', 'cursos_localização', type_='unique')
    # ### end Alembic commands ###
