"""adicionando o modelo cursos no banco

Revision ID: a7b7587bc585
Revises: 3aa6326c2c31
Create Date: 2025-10-01 20:20:07.550188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b7587bc585'
down_revision: Union[str, Sequence[str], None] = '3aa6326c2c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('academic_degree', sa.Enum('BACHARELADO', 'LICENCIATURA', 'TECNOLOGO', 'MESTRADO', 'DOUTORADO', 'ESPECIALIZACAO', 'AREA_DE_INGRESSO_BASICO', 'SEQUENCIAL', 'NAO_IDENTIFICADO', name='degreechoices'), nullable=False),
    sa.Column('workload', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cursos')
    # ### end Alembic commands ###
