"""implementando instancia unica na coluna name de cursos

Revision ID: a7d154836c1e
Revises: 1f6eb35f3969
Create Date: 2025-10-01 20:31:26.491551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d154836c1e'
down_revision: Union[str, Sequence[str], None] = '1f6eb35f3969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    # ### end Alembic commands ###
