"""Atualizando tabela de cursos

Revision ID: ece50f7e11f1
Revises: f86946dd055a
Create Date: 2025-10-04 01:40:53.166277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ece50f7e11f1'
down_revision: Union[str, Sequence[str], None] = 'f86946dd055a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'quantity_vacancies')
    op.drop_column('cursos', 'workload')
    op.drop_column('cursos', 'modality')
    op.drop_column('cursos', 'situation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('situation', postgresql.ENUM('EM_ATIVIDADE', 'EXTINTO', 'EM_EXTINCAO', name='situationchoices'), autoincrement=False, nullable=True))
    op.add_column('cursos', sa.Column('modality', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cursos', sa.Column('workload', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('cursos', sa.Column('quantity_vacancies', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
