"""adicionando a tabela de cursos-Locazicações

Revision ID: f724f2e81610
Revises: 
Create Date: 2025-10-06 09:32:17.681384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f724f2e81610'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos_localização',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('workload', sa.Float(), nullable=True),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('situation', sa.String(), nullable=False),
    sa.Column('quantity_vacancies', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['municipios.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_localização_id'), 'cursos_localização', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cursos_localização_id'), table_name='cursos_localização')
    op.drop_table('cursos_localização')
    # ### end Alembic commands ###
