"""alterando as colunas city_id e id da tabela cursos

Revision ID: f86946dd055a
Revises: 6d92ae044816
Create Date: 2025-10-03 15:54:13.977301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86946dd055a'
down_revision: Union[str, Sequence[str], None] = '6d92ae044816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cursos_city_id_fkey'), 'cursos', type_='foreignkey')
    op.drop_column('cursos', 'city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('cursos_city_id_fkey'), 'cursos', 'municipios', ['city_id'], ['id'])
    # ### end Alembic commands ###
